package com.atlastechnologies.tracecore;
import android.app.*;import android.content.*;import android.location.Location;import android.os.*;import androidx.core.app.NotificationCompat;import com.google.android.gms.location.*;import org.json.*;import java.util.*;
public class LocationService extends Service{
 FusedLocationProviderClient fused;LocationCallback cb;Handler h=new Handler(Looper.getMainLooper());String base,dt;Runnable beat;
 public void onCreate(){super.onCreate();base=Prefs.get(this,"base",BuildConfig.TRACECORE_BASE_URL);dt=Prefs.get(this,"deviceToken","");startForeground(7,notification("TraceCore protection active"));fused=LocationServices.getFusedLocationProviderClient(this);startUpdates();beat=()->{heartbeat();h.postDelayed(beat,300000);};h.post(beat);}
 Notification notification(String text){NotificationManager m=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26)m.createNotificationChannel(new NotificationChannel("tracecore","TraceCore",NotificationManager.IMPORTANCE_LOW));return new NotificationCompat.Builder(this,"tracecore").setSmallIcon(android.R.drawable.ic_lock_lock).setContentTitle("TraceCore").setContentText(text).setOngoing(true).build();}
 void startUpdates(){try{LocationRequest r=new LocationRequest.Builder(Priority.PRIORITY_HIGH_ACCURACY,60000).setMinUpdateIntervalMillis(30000).setWaitForAccurateLocation(false).build();cb=new LocationCallback(){public void onLocationResult(LocationResult x){for(Location l:x.getLocations())sendLocation(l);}};fused.requestLocationUpdates(r,cb,Looper.getMainLooper());}catch(SecurityException ignored){}}
 void sendLocation(Location l){try{JSONObject b=new JSONObject().put("latitude",l.getLatitude()).put("longitude",l.getLongitude()).put("accuracy",l.hasAccuracy()?l.getAccuracy():0).put("timestamp",new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'") {{ setTimeZone(java.util.TimeZone.getTimeZone("UTC")); }}.format(new java.util.Date(l.getTime()))).put("source","gps");ApiClient.call(base,"/api/device/location","POST",dt,b);}catch(Exception e){queue(l);}}
 void queue(Location l){try{String old=Prefs.get(this,"queue","[]");JSONArray a=new JSONArray(old);if(a.length()>=100)a.remove(0);a.put(new JSONObject().put("latitude",l.getLatitude()).put("longitude",l.getLongitude()).put("accuracy",l.hasAccuracy()?l.getAccuracy():0).put("timestamp",new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'") {{ setTimeZone(java.util.TimeZone.getTimeZone("UTC")); }}.format(new java.util.Date(l.getTime()))).put("source","offline_queue"));Prefs.put(this,"queue",a.toString());}catch(Exception ignored){}}
 void flush(){try{JSONArray a=new JSONArray(Prefs.get(this,"queue","[]"));JSONArray left=new JSONArray();for(int i=0;i<a.length();i++){try{ApiClient.call(base,"/api/device/location","POST",dt,a.getJSONObject(i));}catch(Exception e){left.put(a.getJSONObject(i));}}Prefs.put(this,"queue",left.toString());}catch(Exception ignored){}}
 void heartbeat(){if(dt.isEmpty())return;try{JSONObject x=ApiClient.call(base,"/api/device/heartbeat","POST",dt,new JSONObject().put("appVersion","10.1.0"));flush();if(x.optBoolean("shouldLock"))DeviceAdminHelper.lock(this);if(x.optBoolean("shouldAlarm"))notifyAlert();}catch(Exception ignored){}}
 void notifyAlert(){NotificationManager m=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26)m.createNotificationChannel(new NotificationChannel("alert","TraceCore Alerts",NotificationManager.IMPORTANCE_HIGH));m.notify(99,new NotificationCompat.Builder(this,"alert").setSmallIcon(android.R.drawable.ic_dialog_alert).setContentTitle("TraceCore security alert").setContentText("This device is marked lost or stolen.").setPriority(NotificationCompat.PRIORITY_MAX).setAutoCancel(true).build());}
 public int onStartCommand(Intent i,int f,int s){return START_STICKY;}public void onDestroy(){if(cb!=null)fused.removeLocationUpdates(cb);h.removeCallbacksAndMessages(null);super.onDestroy();}public android.os.IBinder onBind(Intent i){return null;}
}
