package com.atlastechnologies.tracecore;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.*;import android.provider.Settings;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import org.json.*;
public class MainActivity extends AppCompatActivity{
 EditText base,email,password,name,serial,imei;TextView status,credential;String auth="";
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);base=findViewById(R.id.baseUrl);email=findViewById(R.id.email);password=findViewById(R.id.password);name=findViewById(R.id.deviceName);serial=findViewById(R.id.serial);imei=findViewById(R.id.imei);status=findViewById(R.id.status);credential=findViewById(R.id.credential);base.setText(Prefs.get(this,"base",BuildConfig.TRACECORE_BASE_URL));email.setText(Prefs.get(this,"email",""));name.setText("My Android");findViewById(R.id.login).setOnClickListener(v->login());findViewById(R.id.register).setOnClickListener(v->register());findViewById(R.id.enable).setOnClickListener(v->enable());findViewById(R.id.stop).setOnClickListener(v->{Prefs.bool(this,"tracking",false);stopService(new Intent(this,LocationService.class));status.setText("GPS service stopped");});findViewById(R.id.admin).setOnClickListener(v->startActivity(new Intent(Settings.ACTION_SECURITY_SETTINGS)));}
 String base(){String x=base.getText().toString().trim();Prefs.put(this,"base",x);return x;}
 void login(){new Thread(()->{try{JSONObject d=ApiClient.call(base(),"/api/auth/login","POST","",new JSONObject().put("email",email.getText().toString().trim()).put("password",password.getText().toString()));auth=d.getString("token");Prefs.put(this,"auth",auth);Prefs.put(this,"email",email.getText().toString().trim());runOnUiThread(()->status.setText("Signed in as "+d.optJSONObject("user").optString("name")));}catch(Exception e){runOnUiThread(()->status.setText("Login: "+e.getMessage()));}}).start();}
 void register(){auth=Prefs.get(this,"auth",auth);if(auth.isEmpty()){status.setText("Sign in first");return;}new Thread(()->{try{JSONObject d=ApiClient.call(base(),"/api/devices/register","POST",auth,new JSONObject().put("deviceName",name.getText().toString()).put("platform","Android").put("manufacturer",android.os.Build.MANUFACTURER).put("model",android.os.Build.MODEL).put("serialNumber",serial.getText().toString()).put("imei",imei.getText().toString()).put("managementMode",DeviceAdminHelper.isOwner(this)?"managed":"personal").put("enrollmentState",DeviceAdminHelper.isOwner(this)?"managed":"enrolled"));Prefs.put(this,"deviceToken",d.getString("deviceToken"));Prefs.put(this,"recoveryId",d.getString("recoveryId"));runOnUiThread(()->{credential.setText("Recovery ID: "+d.optString("recoveryId")+"\nDevice token: "+d.optString("deviceToken"));status.setText("Device registered. Save the credential above.");});}catch(Exception e){runOnUiThread(()->status.setText("Register: "+e.getMessage()));}}).start();}
 void enable(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.POST_NOTIFICATIONS},20);if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},21);return;}Prefs.bool(this,"tracking",true);ContextCompat.startForegroundService(this,new Intent(this,LocationService.class));status.setText("GPS protection enabled");}
}
